import type { TournamentConfig } from '@/types';
import { DEFAULT_VISIBILITY } from '@/types';

// Sensible starting point for the Create Tournament wizard — every field is editable by
// the admin in a later step; this just avoids forcing them to fill in everything before
// they can see a preview. Intentionally mirrors KOC's own long-standing defaults (4-game
// sets, 1 singles + 2 doubles pairs, group + knockout playoffs) since that's a well-worn,
// known-good configuration, not because anything here is KOC-specific or hardcoded.
export function buildDefaultTournamentConfig(): TournamentConfig {
  return {
    info: {
      name: '',
      season: '',
      clubName: '',
      leagueName: '',
      description: '',
      rulesText: '',
      shortName: '',
      logoUrl: null,
      bannerUrl: null,
      primaryColor: '#2563eb',
      secondaryColor: '#1e293b',
      theme: 'default',
      location: '',
      organizer: '',
      contactEmail: '',
      website: '',
      registrationOpensAt: null,
      registrationClosesAt: null,
      startsAt: null,
      endsAt: null,
      timezone: Intl.DateTimeFormat().resolvedOptions().timeZone,
      maxRegistrations: null,
    },
    type: 'KOC_LEAGUE',
    structure: {
      groupCount: 2,
      teamCount: 16,
      playersPerTeam: 7,
      captainRequired: true,
      viceCaptainRequired: false,
      benchPlayers: 0,
      reservePlayers: 0,
      maxPlayers: 7,
      minPlayers: 5,
      maxTeams: 16,
      minTeams: 4,
    },
    playerConfig: {
      minAge: null,
      maxAge: null,
      genderRule: 'ANY',
      utrRequired: false,
      ntrpRequired: false,
      skillRatingRequired: false,
      country: null,
      state: null,
      city: null,
      membershipRequired: false,
      registrationFee: 0,
      approvalRequired: false,
      waitlistEnabled: false,
      maxRegistrations: null,
    },
    matchTypes: [
      { code: 'SINGLES', label: 'Singles', enabled: true, playersPerSide: 1 },
      { code: 'DOUBLES', label: 'Doubles', enabled: true, playersPerSide: 2 },
      { code: 'REVERSE_DOUBLES', label: 'Reverse Doubles', enabled: true, playersPerSide: 2 },
      { code: 'MIXED_DOUBLES', label: 'Mixed Doubles', enabled: false, playersPerSide: 2 },
    ],
    lineup: [
      { matchType: 'SINGLES', count: 1 },
      { matchType: 'DOUBLES', count: 2 },
      { matchType: 'REVERSE_DOUBLES', count: 2 },
    ],
    scoring: {
      setFormat: 'FOUR_GAME_SET',
      tiebreakFormat: 'TEN_POINT',
      adRule: 'NO_AD',
      gamesPerSet: 4,
      setsToWin: 2,
      setTiebreakMinPoints: 7,
      setTiebreakWinBy: 2,
      matchTiebreakMinPoints: 10,
      matchTiebreakWinBy: 2,
      allowWalkover: true,
      allowRetired: true,
      allowIncomplete: false,
      allowRainSuspended: true,
      allowCancelled: true,
    },
    standings: {
      tiebreakOrder: ['POINTS', 'SETS_WON', 'GAME_DIFF', 'GAMES_WON', 'HEAD_TO_HEAD'],
      pointsPerWin: 1,
      pointsPerLoss: 0,
      bonusPointsEnabled: false,
      penaltyPointsEnabled: false,
      customFormula: null,
    },
    playoffs: {
      enabled: true,
      qualifyPerGroup: 4,
      hasQuarterFinal: false,
      hasSemiFinal: true,
      hasFinal: true,
      hasThirdPlaceMatch: false,
      hasConsolationDraw: false,
      hasBronzeMatch: false,
      seedingMethod: 'AUTOMATIC',
    },
    registration: {
      mode: 'INVITE_ONLY',
      approvalMode: 'ADMIN_APPROVAL',
      paid: false,
      waitlistEnabled: false,
      replacementPlayersAllowed: true,
      closesAutomaticallyAtCapacity: false,
    },
    visibility: { ...DEFAULT_VISIBILITY },
    branding: {
      logoUrl: null,
      bannerUrl: null,
      backgroundUrl: null,
      themeColor: '#2563eb',
      accentColor: '#f59e0b',
      fontFamily: null,
      sponsorImageUrls: [],
      clubLogoUrl: null,
      partnerLogoUrls: [],
      socialLinks: {},
      faviconUrl: null,
    },
    // Mirrors koc3-app's long-standing eligibilityRules.js defaults (2 singles / 6 total /
    // 3 partner days, no singles+doubles same match day) — a known-good starting point,
    // fully editable in Settings, not KOC-specific.
    eligibility: {
      enabled: true,
      maxSinglesDaysPerPlayer: 2,
      maxTotalMatchDaysPerPlayer: 6,
      maxPartnerDaysPerPair: 3,
      allowSinglesAndDoublesSameDay: false,
    },
  };
}
